[package]
name = "server"
version = "0.1.0"
edition = "2021"
description = "A server that echoes stuff"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
